export const quillModules = {
    toolbar: [
        [{ font: [] }],
        [{ header: [1, 2, 3, 4, 5, 6, false] }, { size: ["small", false, "large", "huge"] }],
        ["bold", "italic", "underline", "strike"],
        [{ color: [] }, { background: [] }],
        [{ script: "sub" }, { script: "super" }],
        [{ list: "ordered" }, { list: "bullet" }, { list: "check" }],
        [{ indent: "-1" }, { indent: "+1" }],
        [{ align: [] }, { direction: "rtl" }],
        ["blockquote", "code-block", "code"],
        ["link", "image", "video"],
        ["clean"],
    ],
    history: {
        delay: 500,
        maxStack: 100,
        userOnly: true,
    },
};

export const quillFormats = [
    "font",
    "header",
    "size",
    "bold",
    "italic",
    "underline",
    "strike",
    "color",
    "background",
    "script",
    "list",
    "indent",
    "align",
    "direction",
    "blockquote",
    "code-block",
    "code",
    "link",
    "image",
    "video",
];
